---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          searchPaths: ConfigData
          repos:
            hello:
              uri: https://github.com/hocklo/Microservices-With-Spring-Student-Files
              searchPaths: ConfigData  
server:
  port: 8001